name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to your default branch if it's not 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21' # Use the Node.js version that matches your development environment

    - name: Install Dependencies
      run: npm install

    - name: List Root Directory
      run: ls -alh

    - name: Build Project and Show Output
      env:
        BASE_URL: '/nBody/'
      run: npm run build | tee build-output.log
      working-directory: ./
    
    - name: List Output Directory
      run: pwd && ls -alh

    - name: List Dist Directory
      run: ls -alh dist/

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: dist
        token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
        clean: true

