name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to your default branch if it's not 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Use the Node.js version that matches your development environment

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      env:
        BASE_URL: '/repository-name/'  # Replace with the path of your GitHub Pages site
      run: npm run build

  - name: Deploy to GitHub Pages
    uses: JamesIves/github-pages-deploy-action@4.1.4
    with:
      branch: gh-pages
      folder: dist  # This should be just 'dist', not 'nBody/dist' or similar
      clean: true

